defaults: &defaults
    parallelism: 1
    working_directory: ~/workspace
    docker:
      - image: 421990735784.dkr.ecr.us-east-1.amazonaws.com/ci-build-environment:ruby-2.6-stretch
        aws_auth:
          aws_access_key_id: $AWS_ACCESS_KEY_ID
          aws_secret_access_key: $AWS_SECRET_ACCESS_KEY
version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install aws cli
          command: sudo apt-get install -y awscli
      - run: aws s3 cp s3://flipp-platform-production/platform-param-decrypt/platform-param-decrypt_linux platform-param-decrypt_linux
      - run: chmod +x platform-param-decrypt_linux
      - run: mkdir vendor
      - run: sudo chmod 1777 -R /home/circleci/.bundle /tmp
      - run: ./platform-param-decrypt_linux -bundleConfig > ~/.bundle/config

      # Restore bundle cache & npm cache
      - restore_cache:
          key: 'rails-{{ checksum "Gemfile.lock" }}'

      # Bundle install dependencies in /tmp/
      # so Dockerfile does not copy them since
      # its base image is different than CircleCI
      - run:
          name: Bundle install
          command: bundle install --path vendor/bundle --jobs=4 --retry=3

      # Store bundle cache
      - save_cache:
          key: 'rails-{{ checksum "Gemfile.lock" }}'
          paths:
            - ~/workspace/vendor/bundle

      - persist_to_workspace:
          # Must be an absolute path, or relative path from working_directory
          root: ~/workspace
          # Must be relative path from root
          paths:
            - .

  deploy-to-prod:
    <<: *defaults
    working_directory: ~/workspace

    steps:
      - checkout
      - run: chmod +x ./deploy/artifactory.sh && ./deploy/artifactory.sh

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy-to-prod:
           requires:
             - build
           filters:
             branches:
               only:
               - main
